# Generated by Django 5.2.3 on 2025-06-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_unit', models.CharField(default='grams', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
